import { invoke, type InvokeArgs } from "@tauri-apps/api/core";

/// One member per `#[tauri::command]` in src-tauri/src/lib.rs; a backend test
/// reads this file and fails when the two lists differ.
export type CommandName =
  | "add_tag_to_asset"
  | "add_tag_to_assets"
  | "analyze_assets"
  | "apply_naming_fixes"
  | "can_undo"
  | "cancel_scan"
  | "check_project_paths"
  | "clear_scan_cache"
  | "clear_thumbnail_cache"
  | "clear_undo_history"
  | "copy_assets"
  | "create_tag"
  | "delete_assets"
  | "delete_tag"
  | "duplicate_assets"
  | "ensure_project_config"
  | "estimate_learning_cost"
  | "execute_batch_rename"
  | "export_issues_to_json"
  | "export_to_csv"
  | "export_to_html"
  | "export_to_json"
  | "find_unused_assets"
  | "get_all_asset_tags"
  | "get_all_tags"
  | "get_git_info"
  | "get_git_statuses"
  | "get_godot_dependencies"
  | "get_godot_project_info"
  | "get_project_stats"
  | "get_thumbnail"
  | "get_thumbnail_cache_size"
  | "get_undo_history"
  | "get_unity_dependencies"
  | "get_unity_file_info"
  | "get_unity_project_info"
  | "get_unreal_project_info"
  | "godot_asset_references"
  | "learn_project_conventions"
  | "llm_cache_size"
  | "llm_clear_cache"
  | "llm_estimate_cost"
  | "llm_ollama_models"
  | "llm_suggest_tags"
  | "move_assets"
  | "open_in_editor"
  | "open_url"
  | "open_with_default_app"
  | "preview_batch_rename"
  | "preview_naming_fixes"
  | "read_ai_rules"
  | "read_project_config"
  | "read_project_meta"
  | "register_project"
  | "remove_tag_from_asset"
  | "rename_file"
  | "resolve_texture_siblings"
  | "save_ai_rules"
  | "save_text_file"
  | "scan_project_incremental"
  | "show_in_file_manager"
  | "start_watching"
  | "stop_watching"
  | "suggest_tags"
  | "toggle_devtools"
  | "undo_last_operation"
  | "unregister_project"
  | "update_tag"
  | "write_project_meta";

/// `invoke` narrowed to the registered commands: a misspelt name is a type error
/// here instead of a "command not found" rejection at runtime.
export function call<T>(command: CommandName, args?: InvokeArgs): Promise<T> {
  return invoke<T>(command, args);
}
