//! Persistence for AI-Learning-derived heuristic rules.
//!
//! Stored in `<project_root>/tidycraft.ai.toml` — separate from
//! user-edited `tidycraft.toml` so program writes don't trample user
//! edits and (more importantly) the user's analyzer config doesn't
//! force-validate against AI-only fields.
//!
//! File header comment warns the user not to hand-edit; re-running
//! AI Learning rewrites the whole file. (Power users can edit anyway —
//! the toml round-trips fine, they just lose comments.)
//!
//! Schema (top-level):
//! ```toml
//! # generated by Tidycraft AI Learning — manual edits will be overwritten
//! last_learned    = "2026-05-09T14:30:00Z"
//! prompt_version  = 1
//! sampling_depth  = 5
//! provider_used   = "openai"
//! model_used      = "gpt-5.4-mini"
//!
//! [[rules]]
//! kind       = "filename_token"
//! pattern    = "BaseColor"
//! tags       = ["diffuse-map"]
//! confidence = 0.95
//! ```

use std::fs;
use std::path::Path;

use serde::{Deserialize, Serialize};

use super::learning::LearnedRule;

const FILE_NAME: &str = "tidycraft.ai.toml";

const HEADER: &str = "# This file is generated by Tidycraft AI Learning.\n\
# Manual edits will be overwritten on the next learning run.\n\
# To customize rules, use the AI Review panel in the app.\n\n";

/// On-disk shape. `last_learned` is an ISO-8601-ish UTC string we
/// generate from `chrono::Utc::now()`; we keep it as a string rather
/// than a typed datetime so the toml stays human-readable and we don't
/// have to pull a chrono dep beyond what the project already has.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct AiRulesDoc {
    /// ISO 8601 UTC timestamp of the last learning run.
    pub last_learned: String,
    /// Mirrors `learning::LEARNING_PROMPT_VERSION` at the time of write.
    /// Frontend can compare against the current value to nudge a
    /// re-learn when the prompt schema has moved on.
    pub prompt_version: u32,
    /// Sampling depth that produced these rules. Surfaced in the
    /// review UI ("learned with depth=5").
    pub sampling_depth: usize,
    /// `claude` / `openai` / `ollama` — for diagnostics + UI display.
    pub provider_used: String,
    /// e.g. `claude-sonnet-4-6`. Same purpose as `provider_used`.
    pub model_used: String,
    /// The rules themselves, in the order the LLM emitted them. Order
    /// matters for predictability when an asset matches multiple rules
    /// at the same confidence (RuleSuggester takes the first hit at
    /// each tier).
    #[serde(default)]
    pub rules: Vec<LearnedRule>,
}

impl AiRulesDoc {
    pub fn project_path(project_root: &Path) -> std::path::PathBuf {
        project_root.join(FILE_NAME)
    }

    /// Serialize to toml + write to disk with a header comment.
    /// Errors propagate so callers can decide whether a write failure
    /// is fatal (Day 6 plan: log + continue — losing the persisted
    /// rules just means the user has to re-learn).
    pub fn save(&self, project_root: &Path) -> Result<(), String> {
        let body = toml::to_string_pretty(self).map_err(|e| e.to_string())?;
        let content = format!("{HEADER}{body}");
        let path = Self::project_path(project_root);
        fs::write(&path, content).map_err(|e| e.to_string())
    }

    /// Read from disk if present. Returns `Ok(None)` for the common
    /// "no learning has run yet" case, `Err` only for genuine IO /
    /// parse failures (which the UI can surface as "rule store is
    /// corrupt; re-learn?").
    pub fn load(project_root: &Path) -> Result<Option<Self>, String> {
        let path = Self::project_path(project_root);
        if !path.exists() {
            return Ok(None);
        }
        let content = fs::read_to_string(&path).map_err(|e| e.to_string())?;
        let doc: AiRulesDoc = toml::from_str(&content).map_err(|e| e.to_string())?;
        Ok(Some(doc))
    }

    /// Delete the file. Used for "Clear AI rules" Settings action
    /// (Day 8). No-op if the file doesn't exist.
    #[allow(dead_code)]
    pub fn clear(project_root: &Path) -> Result<(), String> {
        let path = Self::project_path(project_root);
        if !path.exists() {
            return Ok(());
        }
        fs::remove_file(&path).map_err(|e| e.to_string())
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::tempdir;

    fn sample_doc() -> AiRulesDoc {
        AiRulesDoc {
            last_learned: "2026-05-09T12:00:00Z".into(),
            prompt_version: 1,
            sampling_depth: 5,
            provider_used: "openai".into(),
            model_used: "gpt-5.4-mini".into(),
            rules: vec![
                LearnedRule::FilenameToken {
                    pattern: "BaseColor".into(),
                    tags: vec!["diffuse-map".into()],
                    confidence: 0.95,
                },
                LearnedRule::PathPrefix {
                    pattern: "Characters/Hero/".into(),
                    tags: vec!["hero".into()],
                    confidence: 0.99,
                },
            ],
        }
    }

    #[test]
    fn save_then_load_round_trips() {
        let dir = tempdir().unwrap();
        let doc = sample_doc();
        doc.save(dir.path()).unwrap();
        let loaded = AiRulesDoc::load(dir.path()).unwrap().unwrap();
        assert_eq!(doc, loaded);
    }

    #[test]
    fn load_returns_none_when_file_absent() {
        let dir = tempdir().unwrap();
        let result = AiRulesDoc::load(dir.path()).unwrap();
        assert!(result.is_none());
    }

    #[test]
    fn save_writes_warning_header_comment() {
        let dir = tempdir().unwrap();
        sample_doc().save(dir.path()).unwrap();
        let raw = fs::read_to_string(AiRulesDoc::project_path(dir.path())).unwrap();
        assert!(raw.starts_with("# This file is generated by Tidycraft AI Learning."));
        assert!(raw.contains("Manual edits will be overwritten"));
    }

    #[test]
    fn rules_serialize_with_kind_tag() {
        // Confirm toml serialization preserves the `kind = "..."` tag
        // on each rule entry — frontend / round-trip relies on this.
        let dir = tempdir().unwrap();
        sample_doc().save(dir.path()).unwrap();
        let raw = fs::read_to_string(AiRulesDoc::project_path(dir.path())).unwrap();
        assert!(raw.contains("kind = \"filename_token\""));
        assert!(raw.contains("kind = \"path_prefix\""));
    }

    #[test]
    fn clear_removes_file() {
        let dir = tempdir().unwrap();
        sample_doc().save(dir.path()).unwrap();
        assert!(AiRulesDoc::project_path(dir.path()).exists());
        AiRulesDoc::clear(dir.path()).unwrap();
        assert!(!AiRulesDoc::project_path(dir.path()).exists());
    }

    #[test]
    fn clear_is_noop_when_file_absent() {
        let dir = tempdir().unwrap();
        // Should not error.
        AiRulesDoc::clear(dir.path()).unwrap();
    }

    #[test]
    fn corrupt_toml_returns_err_not_none() {
        let dir = tempdir().unwrap();
        fs::write(AiRulesDoc::project_path(dir.path()), "not valid = toml [").unwrap();
        let result = AiRulesDoc::load(dir.path());
        assert!(result.is_err());
    }
}
